ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

ROTOR_WIRING = {
    "I": "EKMFLGDQVZNTOWYHXUSPAIBRCJ",
    "II": "AJDKSIRUXBLHWTMCQGZNPYFVOE",
    "III": "BDFHJLCPRTXVZNYEIWGAKMUSQO",
    "IV": "ESOVPZJAYQUIRHXLNFTGKDCMWB",
    "V": "VZBRGITYUPSDNHLXAWMJQOFECK"
}

ROTOR_NOTCHES = {  # Notch positions are represented by the letter that follows the notch
    "I": "R",
    "II": "F",
    "III": "W",
    "IV": "K",
    "V": "A"
}

REFLECTOR_WIRING = {
    "B": "YRUHQSLDPXNGOKMIEBFZCWVJAT",
    "C": "FVPJIAOYEDRZXWGCTKUQSBNMHL"
}
