name: Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 mypy coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Type checking with MyPy
        run: |
          mypy -p pyenigma --strict
      - name: Test with pytest
        run: |
          pytest -v
      - name: Code coverage with Coverage.py
        run: |
          coverage run -m pytest
          coverage report
          coverage xml
      - name: Code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
