name: Tests

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - ".gitignore"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: uv sync
      - name: Type checking with MyPy
        run: uv run mypy -p pyenigma
      - name: Test with pytest
        run: uv run pytest -v
      - name: Code coverage with Coverage.py
        run: |
          uv run coverage run -m pytest
          uv run coverage report
          uv run coverage xml
      - name: Code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
